### ISSUE TITLE
Additional issues

### ISSUE THREAD

**Issue by jamesuanhoro** [JoshSchramm94/validateHOT#3]
- [x] README references a vignette, I don't find it when I run `vignette(package = "validateHOT")`, appears to be WIP
- [x] Provide a means for community members to contribute to the development of the package, this is required by JOSS
- [x] The typical workflow section in the paper should show the required packages for the code in the paper. One can infer they need to load `validateHOT`, but inexperienced R users may not realize they also need `dplyr`.

openjournals/joss-reviews/issues/6708

**Comment by JoshSchramm94** [comment]
@jamesuanhoro, thank you very much for your valuable feedback as well as taking your time to review the paper and the package. I now updated everything and also added a contributing file as well as a conde of conduct. I also updated the workflow in the paper to ensure that readers are aware they need the `dplyr` package as well. Once again thanks for your feedback.
